services:

  broker1:
    image: apache/kafka:latest
    hostname: broker1
    container_name: broker1
    restart: unless-stopped
    networks:
      - test-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_MS: "9000000"
      KAFKA_LOG_RETENTION_BYTES: "2147483648"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29093 #,2@broker2:29093,3@broker3:29093
      KAFKA_LISTENERS: PLAINTEXT://broker1:29092,CONTROLLER://broker1:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs-1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z broker1 29092 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    depends_on:
      broker1:
        condition: service_healthy
    volumes:
      - ./docker/kafka/init_topic.sh:/init_topic.sh
    command: [ "/bin/sh", "/init_topic.sh" ]
    networks:
      - test-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    networks:
      - test-net
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1:29092

  jobmanager:
    image: flink:2.3.0-scala_2.12
    container_name: jobmanager
    ports:
      - "8084:8081"
    command: jobmanager
    networks:
      - test-net
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: flink:2.3.0-scala_2.12
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    networks:
      - test-net
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 

#  clickhouse:
#    image: clickhouse/clickhouse-server
#    container_name: clickhouse
#    restart: unless-stopped
#    networks:
#      - test-net
#    ports:
#      - "8123:8123"
#      - "9002:9000"
#    environment:
#      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
#
#  tabix:
#    image: spoonest/clickhouse-tabix-web-client
#    container_name: tabix
#    restart: unless-stopped
#    networks:
#      - test-net
#    ports:
#      - "8082:80"
#    depends_on:
#      - clickhouse

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - test-net
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo1:
    image: mongo:latest
    container_name: mongo1
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - test-net
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: adminpass
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db

  mongo-init:
    image: mongo:latest
    container_name: mongo-init
    depends_on:
      - mongo1
    networks:
      - test-net
    command: >
      bash -c "sleep 5 && mongosh --host mongo1:27017 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            {_id: 0, host: \"mongo1:27017\"},
          ]
        })
      '"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      - test-net
    depends_on:
      - mongo1
    environment:
      ME_CONFIG_mongo1_ADMINUSERNAME: admin
      ME_CONFIG_mongo1_ADMINPASSWORD: adminpass
      ME_CONFIG_mongo1_SERVER: mongo1
    ports:
      - "8081:8081"

  connect_debezium_kafka:
    image: quay.io/debezium/connect:2.7
    container_name: connect_debezium_kafka
    ports:
      - "8083:8083"
    networks:
      - test-net
    depends_on:
      - broker1
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=broker1:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  debezium-init:
    image: curlimages/curl:latest
    container_name: debezium-init
    networks:
      - test-net
    depends_on:
      - connect_debezium_kafka
      - mongo-init
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Waiting for Kafka Connect to start..."
        while [ $$(curl -s -o /dev/null -w "%{http_code}" http://connect_debezium_kafka:8083/connectors) -ne 200 ]; do
          sleep 3
        done
        echo "Kafka Connect is ready! Registering MongoDB Connector..."
        curl -s -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" \
          http://connect_debezium_kafka:8083/connectors/ \
          -d '{
            "name": "mongodb-cdc-connector",
            "config": {
              "connector.class": "io.debezium.connector.mongodb.MongoDbConnector",
              "mongodb.connection.string": "mongodb://mongo1:27017/?replicaSet=rs0",
              "topic.prefix": "mongo_cdc",
              "database.include.list": "inventory,ecommerce,crm_db",
              "capture.mode": "change_streams_update_full"
            }
          }'
        echo ""
        echo "Connector initialization completed!"

networks:
  test-net:
    driver: bridge
    name: test-net

volumes:
  postgres_data:
    name: postgres_data
  mongo1_data:
    name: mongo1_data

# docker compose -f docker_compose.yml up -d --build