app:
  name: "Stateful Processing Core"
  env: "dev"
  version: "1.0.0"

kafka:
  bootstrap_servers: "localhost:9092"
  event_topics:
    - "source.event"
  schema_topics:
    - "source.schema"
  group_id: "cdp-flink-group"

database:
  clickhouse:
    url: "jdbc:clickhouse://localhost:8123/cdp"
    user: "default"
    password: ${CLICKHOUSE_PASSWORD:-}