# Kafka Configuration
kafka.bootstrap-servers=localhost:9092
kafka.topic=stream-input-events

# Generator Default Configuration
generator.default.req-per-second=50
generator.default.id-range=1000

# Rule Generator Configuration
rule.output.base-path=rules_output
rule.default.total-rules=100