# Kafka Configuration
kafka.bootstrap-servers=localhost:9092
kafka.topic.raw-event=source.event
kafka.topic.schema=source.schema

# Schema versioning
schema.version=v2

# Generator Configuration
generator.req-per-second=1000000
generator.num-threads=16
